// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Doc = Collections['docs']['schema']['_output']
export declare const docs: Doc[]

export type DraftDoc = Collections['drafts']['schema']['_output']
export declare const drafts: DraftDoc[]
