import fg from "fast-glob"
import fs from "node:fs/promises"
import path from "node:path"
import matter from "gray-matter"

type PostIndexItem = {
  slug: string
  title: string
}

type ContentIndexItem = {
  slug: string
  title: string
  description?: string
  date?: string
  updated?: string
  published?: boolean
  category?: string
  section?: string
  docType?: string
  order?: number
  cover?: string
  featured?: boolean
}

const CONTENT_GLOB = [
  "content/docs/**/*.mdx",
  "content/docs/**/*.md",
  "content/draft/**/*.mdx",
  "content/draft/**/*.md",
  "content/posts/**/*.mdx",
  "content/posts/**/*.md",
]
const OUTPUT_FILE = "generated/posts-index.ts"
const CONTENT_INDEX_OUTPUT_FILE = "generated/content-index.ts"

// 공백 제거 + 문자열 아니면 빈 문자열
function pickString(v: unknown): string {
  return typeof v === "string" ? v.trim() : ""
}

// TS 코드에 안전하게 문자열로 넣기
function tsString(s: string): string {
  return JSON.stringify(s)
}

function pickOptionalString(v: unknown): string | undefined {
  if (v instanceof Date && !Number.isNaN(v.getTime())) {
    return v.toISOString().slice(0, 10)
  }

  const s = pickString(v)
  return s ? s : undefined
}

function pickOptionalNumber(v: unknown): number | undefined {
  return typeof v === "number" && Number.isFinite(v) ? v : undefined
}

function pickOptionalBoolean(v: unknown): boolean | undefined {
  return typeof v === "boolean" ? v : undefined
}

function toIndexItem(data: Record<string, unknown>): ContentIndexItem | undefined {
  const slug = pickString(data.slug)
  const title = pickString(data.title)
  if (!slug || !title) return undefined

  return {
    slug,
    title,
    description: pickOptionalString(data.description),
    date: pickOptionalString(data.date),
    updated: pickOptionalString(data.updated),
    published: pickOptionalBoolean(data.published),
    category: pickOptionalString(data.category),
    section: pickOptionalString(data.section),
    docType: pickOptionalString(data.docType),
    order: pickOptionalNumber(data.order),
    cover: pickOptionalString(data.cover),
    featured: pickOptionalBoolean(data.featured),
  }
}

function serializeValue(v: unknown): string {
  return JSON.stringify(v)
}

function serializeIndexItem(item: ContentIndexItem): string {
  const entries = Object.entries(item).filter(([, value]) => value !== undefined)
  const body = entries
    .map(([key, value]) => `${key}: ${serializeValue(value)}`)
    .join(", ")
  return `  { ${body} },`
}

async function main(): Promise<void> {
  const files = await fg(CONTENT_GLOB, { dot: false })

  const index: PostIndexItem[] = []
  const docsIndex: ContentIndexItem[] = []
  const draftsIndex: ContentIndexItem[] = []
  const blogIndex: ContentIndexItem[] = []
  const missing: Array<{ file: string; missing: string[] }> = []

  for (const file of files) {
    const raw = await fs.readFile(file, "utf8")
    const parsed = matter(raw)
    const data = (parsed.data ?? {}) as Record<string, unknown>

    const slug = pickString(data.slug)
    const title = pickString(data.title)
    const published = data.published

    if (!slug || !title) {
      const miss: string[] = []
      if (!slug) miss.push("slug")
      if (!title) miss.push("title")
      missing.push({ file, missing: miss })
      continue
    }

    const item = toIndexItem(data)
    if (item) {
      if (file.startsWith("content/docs/")) {
        docsIndex.push(item)
      } else if (file.startsWith("content/draft/")) {
        draftsIndex.push(item)
      } else if (file.startsWith("content/posts/")) {
        blogIndex.push(item)
      }
    }

    if (published === false || file.startsWith("content/draft/")) continue

    index.push({ slug, title })
  }

  // frontmatter 누락이 있으면 실패(원하시면 경고로 바꿔드릴 수 있음)
  if (missing.length > 0) {
    const msg = missing
      .map((m) => `- ${m.file} (missing: ${m.missing.join(", ")})`)
      .join("\n")
    throw new Error(`Frontmatter fields missing:\n${msg}`)
  }

  // slug 중복 검사
  const seen = new Set<string>()
  const dup: string[] = []
  for (const p of index) {
    if (seen.has(p.slug)) dup.push(p.slug)
    seen.add(p.slug)
  }
  if (dup.length > 0) {
    throw new Error(
      `Duplicate slugs found in frontmatter: ${Array.from(new Set(dup)).join(", ")}`
    )
  }

  index.sort((a, b) => a.slug.localeCompare(b.slug, "en"))

  const lines = index.map(
    (p) => `  { slug: ${tsString(p.slug)}, title: ${tsString(p.title)} },`
  )

  const out =
    `// AUTO-GENERATED FILE. DO NOT EDIT.\n` +
    `// Generated by scripts/generate-posts-index.ts\n\n` +
    `export type PostIndexItem = {\n` +
    `  slug: string\n` +
    `  title: string\n` +
    `}\n\n` +
    `export const POSTS_INDEX: PostIndexItem[] = [\n` +
    `${lines.join("\n")}\n` +
    `]\n`

  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true })
  await fs.writeFile(OUTPUT_FILE, out, "utf8")

  const sortBySlug = (a: ContentIndexItem, b: ContentIndexItem) =>
    a.slug.localeCompare(b.slug, "en")
  docsIndex.sort(sortBySlug)
  draftsIndex.sort(sortBySlug)
  blogIndex.sort(sortBySlug)

  const contentOut =
    `// AUTO-GENERATED FILE. DO NOT EDIT.\n` +
    `// Generated by scripts/generate-posts-index.ts\n\n` +
    `export type ContentIndexItem = {\n` +
    `  slug: string\n` +
    `  title: string\n` +
    `  description?: string\n` +
    `  date?: string\n` +
    `  updated?: string\n` +
    `  published?: boolean\n` +
    `  category?: string\n` +
    `  section?: string\n` +
    `  docType?: string\n` +
    `  order?: number\n` +
    `  cover?: string\n` +
    `  featured?: boolean\n` +
    `}\n\n` +
    `export const DOCS_INDEX: ContentIndexItem[] = [\n` +
    `${docsIndex.map(serializeIndexItem).join("\n")}\n` +
    `]\n\n` +
    `export const DRAFT_DOCS_INDEX: ContentIndexItem[] = [\n` +
    `${draftsIndex.map(serializeIndexItem).join("\n")}\n` +
    `]\n\n` +
    `export const BLOG_INDEX: ContentIndexItem[] = [\n` +
    `${blogIndex.map(serializeIndexItem).join("\n")}\n` +
    `]\n`

  await fs.writeFile(CONTENT_INDEX_OUTPUT_FILE, contentOut, "utf8")

  console.log(`Generated ${OUTPUT_FILE} (${index.length} posts)`)
  console.log(
    `Generated ${CONTENT_INDEX_OUTPUT_FILE} (${docsIndex.length} docs, ${draftsIndex.length} drafts, ${blogIndex.length} blog posts)`,
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
