import fg from "fast-glob"
import fs from "node:fs/promises"
import path from "node:path"
import matter from "gray-matter"

type PostIndexItem = {
  slug: string
  title: string
}

const CONTENT_GLOB = ["content/**/*.mdx", "content/**/*.md"]
const OUTPUT_FILE = "generated/posts-index.ts"

// 공백 제거 + 문자열 아니면 빈 문자열
function pickString(v: unknown): string {
  return typeof v === "string" ? v.trim() : ""
}

// TS 코드에 안전하게 문자열로 넣기
function tsString(s: string): string {
  return JSON.stringify(s)
}

async function main(): Promise<void> {
  const files = await fg(CONTENT_GLOB, { dot: false })

  const index: PostIndexItem[] = []
  const missing: Array<{ file: string; missing: string[] }> = []

  for (const file of files) {
    const raw = await fs.readFile(file, "utf8")
    const parsed = matter(raw)
    const data = (parsed.data ?? {}) as Record<string, unknown>

    const slug = pickString(data.slug)
    const title = pickString(data.title)

    if (!slug || !title) {
      const miss: string[] = []
      if (!slug) miss.push("slug")
      if (!title) miss.push("title")
      missing.push({ file, missing: miss })
      continue
    }

    index.push({ slug, title })
  }

  // frontmatter 누락이 있으면 실패(원하시면 경고로 바꿔드릴 수 있음)
  if (missing.length > 0) {
    const msg = missing
      .map((m) => `- ${m.file} (missing: ${m.missing.join(", ")})`)
      .join("\n")
    throw new Error(`Frontmatter fields missing:\n${msg}`)
  }

  // slug 중복 검사
  const seen = new Set<string>()
  const dup: string[] = []
  for (const p of index) {
    if (seen.has(p.slug)) dup.push(p.slug)
    seen.add(p.slug)
  }
  if (dup.length > 0) {
    throw new Error(
      `Duplicate slugs found in frontmatter: ${Array.from(new Set(dup)).join(", ")}`
    )
  }

  index.sort((a, b) => a.slug.localeCompare(b.slug, "en"))

  const lines = index.map(
    (p) => `  { slug: ${tsString(p.slug)}, title: ${tsString(p.title)} },`
  )

  const out =
    `/* eslint-disable */\n` +
    `// AUTO-GENERATED FILE. DO NOT EDIT.\n` +
    `// Generated by scripts/generate-posts-index.ts\n\n` +
    `export type PostIndexItem = {\n` +
    `  slug: string\n` +
    `  title: string\n` +
    `}\n\n` +
    `export const POSTS_INDEX: PostIndexItem[] = [\n` +
    `${lines.join("\n")}\n` +
    `]\n`

  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true })
  await fs.writeFile(OUTPUT_FILE, out, "utf8")

  console.log(`Generated ${OUTPUT_FILE} (${index.length} posts)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
